substitutions:
  device_name: "3d-printer-outlet"
  friendly_name: "3D Printer Outlet"
  api_encryption_key: !secret 3d_printer_outlet_api_encryption_key
  fallback_ap_password: !secret 3d_printer_outlet_fallback_ap_password
  ota_password: !secret 3d_printer_outlet_ota_password
  wifi_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid

packages:
  remote_package:
    url: https://github.com/andyattebery/esphome-config
    files:
      - templates/sonoff-s31.yaml
