substitutions:
  device_name: "air-gradient-one-01"
  friendly_name: "Air Gradient One 01"
  api_encryption_key: !secret air_gradient_one_01_api_encryption_key
  fallback_ap_password: !secret air_gradient_one_01_fallback_ap_password
  ota_password: !secret air_gradient_one_01_ota_password
  wifi_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid

packages:
  remote_package:
    url: https://github.com/andyattebery/esphome-config
    files:
      - templates/air-gradient.yaml
