substitutions:
  device_name: "air-gradient"
  friendly_name: "Air Gradient"
  api_encryption_key: !secret air_gradient_api_encryption_key
  fallback_ap_password: !secret air_gradient_fallback_ap_password
  ota_password: !secret air_gradient_ota_password
  wifi_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
packages:
  remote_package:
    url: https://github.com/andyattebery/esphome
    files:
      - templates/air-gradient.yaml
