substitutions:
  device_name: "example-sonoff-s31"
  api_encryption_key: "YlF4NzREa3FzTDdQSjV1a0hTNXd4RjBvWUwyalk5QXE="
  fallback_ap_password: "cGmjScehpiUt"
  ota_password: "l7Gr2Hry0exPPn2CPmlCyU9TW1eT05YZ"
  wifi_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid

packages:
  remote_package:
    url: https://github.com/andyattebery/esphome-configs
    files:
      - packages/base.yaml
      - packages/sonoff-s31.yaml
