substitutions:
  device_name: "outlet-02"
  friendly_name: "outlet-02"
  api_encryption_key: !secret outlet_02_api_encryption_key
  fallback_ap_password: !secret outlet_02_fallback_ap_password
  ota_password: !secret outlet_02_ota_password
  wifi_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid

packages:
  remote_package:
    url: https://github.com/andyattebery/esphome
    files:
      - templates/sonoff-s31.yaml
