substitutions:
  device_name: "proxmox-cluster-outlet"
  friendly_name: "Proxmox Cluster Outlet"
  api_encryption_key: !secret proxmox_cluster_outlet_api_encryption_key
  fallback_ap_password: !secret proxmox_cluster_outlet_fallback_ap_password
  ota_password: !secret proxmox_cluster_outlet_ota_password
  wifi_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid
  enable_button: "false"

packages:
  remote_package:
    url: https://github.com/andyattebery/esphome
    files:
      - templates/kmc-smart-outlet.yaml

wifi:
  ap:
    ssid: "proxmox-cluster-Fallback-AP"
