substitutions:
  device_name: "vm-host-01-outlet"
  friendly_name: "vm-host-01 Outlet"
  api_encryption_key: !secret vm_host_01_outlet_api_encryption_key
  fallback_ap_password: !secret vm_host_01_outlet_fallback_ap_password
  ota_password: !secret vm_host_01_outlet_ota_password
  wifi_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid

packages:
  remote_package:
    url: https://github.com/andyattebery/esphome
    files:
      - templates/sonoff-s31.yaml
