substitutions:
  device_name: "example-air-gradient"
  api_encryption_key: "RDJlTVo4NDluUG9nb2JYZEtkQWlaQkNMNml5VXdZZ2Y="
  fallback_ap_password: "LC0FDqYM6HPO"
  ota_password: "m6Pv6Hzq3IkybqweaQS1k0cEXHfRebsA"
  wifi_password: !secret wifi_password
  wifi_ssid: !secret wifi_ssid

packages:
  remote_package:
    url: https://github.com/andyattebery/esphome-configs
    files:
      - templates/air-gradient.yaml
