# Variables
substitutions:
  device_name: ""
  friendly_name: "${device_name}"
  esphome_project_name: ""
  esphome_project_version: ""
  api_encryption_key: ""
  fallback_ap_password: ""
  ota_password: ""
  wifi_password: ""
  wifi_ssid: ""

# https://esphome.io/components/esphome
esphome:
  name: "${device_name}"
  friendly_name: "${friendly_name}"
  project:
    name: "${esphome_project_name}"
    version: "${esphome_project_version}"

# Enable Home Assistant API
# https://esphome.io/components/api
api:
  encryption:
    key: "${api_encryption_key}"

# Enable over-the-air updates
# https://esphome.io/components/ota
ota:
  password: "${ota_password}"

# Set WiFi credentials
# https://esphome.io/components/wifi
wifi:
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"

  # Enable fallback access point in case wifi connection fails
  ap:
    ssid: "${device_name}-Fallback-AP"
    password: "${fallback_ap_password}"

# Enable captive portal for fallback access point
# https://esphome.io/components/captive_portal
captive_portal:
