# Variables
substitutions:
  device_name: ""

# Core ESPHome config
# https://esphome.io/components/esphome
esphome:
  name: "${device_name}"
  project:
    name: "KMC.SmartOutlet"
    version: "1.0"
# https://esphome.io/components/esp8266.html
esp8266:
  board: esp01_1m
# https://esphome.io/guides/creators#relevant-documentation
dashboard_import:
  package_import_url: github://andyattebery/esphome-configs/packages/kmc-smart-outlet.yaml
  import_full_config: false

# Enable logging
# https://esphome.io/components/logger
logger:

# Configure sensors
# https://esphome.io/components/sensor/
sensor:
  # https://esphome.io/components/sensor/hlw8012.html
  - platform: hlw8012
    sel_pin: GPIO12
    cf_pin: GPIO4
    cf1_pin: GPIO5
    current:
      name: "${device_name} Current"
    voltage:
      name: "${device_name} Voltage"
    power:
      name: "${device_name} Power"
    energy:
      name: "${device_name} Energy"
    update_interval: 60s

# Configure status LED
# https://esphome.io/components/light/status_led
status_led:
  pin:
    number: GPIO1
    inverted: yes

# Configure switches
# https://esphome.io/components/switch/
switch:
  # https://esphome.io/components/switch/gpio
  - platform: gpio
    name: "${device_name} Switch 1"
    pin: GPIO15
    # inverted: yes
    id: relay1
  - platform: gpio
    name: "${device_name} Switch 2"
    pin: GPIO13
    # inverted: yes
    id: relay2
  - platform: gpio
    name: "${device_name} Switch 3"
    pin: GPIO14
    # inverted: yes
    id: relay3
